### ISSUE TITLE
Missing 'metaeditor.settings' file

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#2]
Running 'python manage.py ' Fails. 

[eric@gala metaeditor]$ python manage.py -h
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Python/2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'metaeditor.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named dj_database_url

**Comment by Pthinker** [comment]
You need to run 
pip install -r requirements.txt
to install all required modules
